repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
        # python, js and ts only
        files: \.(py|js|ts)$
      - id: mixed-line-ending
        files: \.(py|js|ts)$
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: validate-starter-projects
        name: Validate Starter Project Templates
        entry: uv run python src/backend/tests/unit/template/test_starter_projects.py
        language: system
        files: ^src/backend/base/langflow/initial_setup/starter_projects/.*\.json$
        pass_filenames: false
        args: [--security-check]
