"""add_rbac_tables

Revision ID: a20a7041e437
Revises: 3162e83e485f
Create Date: 2025-11-04 10:03:29.763561

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a20a7041e437"
down_revision: str | None = "3162e83e485f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scope_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permission_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_permission_scope_type"), ["scope_type"], unique=False)

    op.create_table(
        "role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_name"), ["name"], unique=True)

    op.create_table(
        "role_permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permission.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id", name="unique_role_permission"),
    )
    with op.batch_alter_table("role_permission", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_permission_permission_id"), ["permission_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_role_permission_role_id"), ["role_id"], unique=False)

    op.create_table(
        "user_role_assignment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=True),
        sa.Column("is_immutable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", "scope_type", "scope_id", name="unique_user_role_scope"),
    )
    with op.batch_alter_table("user_role_assignment", schema=None) as batch_op:
        batch_op.create_index("idx_scope_lookup", ["user_id", "scope_type", "scope_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_role_assignment_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_role_assignment_scope_id"), ["scope_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_role_assignment_scope_type"), ["scope_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_role_assignment_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_role_assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_role_assignment_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_role_assignment_scope_type"))
        batch_op.drop_index(batch_op.f("ix_user_role_assignment_scope_id"))
        batch_op.drop_index(batch_op.f("ix_user_role_assignment_role_id"))
        batch_op.drop_index("idx_scope_lookup")

    op.drop_table("user_role_assignment")
    with op.batch_alter_table("role_permission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_permission_role_id"))
        batch_op.drop_index(batch_op.f("ix_role_permission_permission_id"))

    op.drop_table("role_permission")
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_name"))

    op.drop_table("role")
    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permission_scope_type"))
        batch_op.drop_index(batch_op.f("ix_permission_name"))

    op.drop_table("permission")
    # ### end Alembic commands ###
