"""add_rbac_tables

Revision ID: a20a7041e437
Revises: 3162e83e485f
Create Date: 2025-11-04 10:03:29.763561

This migration creates the complete RBAC schema with all tables in their final state:
- Permission table with action/scope enums
- Role table with is_global field
- RolePermission junction table
- UserRoleAssignment table with polymorphic scope support
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a20a7041e437"
down_revision: Union[str, None] = "3162e83e485f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    # Create permission table if it doesn't exist (with final schema)
    if "permission" not in existing_tables:
        op.create_table(
            "permission",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # Final: action enum
            sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # Final: scope enum
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("action", "scope", name="unique_action_scope"),
        )

    # Create indexes for permission table if they don't exist
    if "permission" in inspector.get_table_names():
        existing_indexes = [idx["name"] for idx in inspector.get_indexes("permission")]
        with op.batch_alter_table("permission", schema=None) as batch_op:
            if "ix_permission_action" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_permission_action"), ["action"], unique=False)
            if "ix_permission_scope" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_permission_scope"), ["scope"], unique=False)

    # Create role table if it doesn't exist (with final schema including is_global)
    if "role" not in existing_tables:
        op.create_table(
            "role",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("is_system", sa.Boolean(), nullable=False),
            sa.Column("is_global", sa.Boolean(), nullable=False, server_default=sa.false()),  # Final: includes is_global
            sa.PrimaryKeyConstraint("id"),
        )

    # Create indexes for role table if they don't exist
    if "role" in inspector.get_table_names():
        existing_indexes = [idx["name"] for idx in inspector.get_indexes("role")]
        with op.batch_alter_table("role", schema=None) as batch_op:
            if "ix_role_name" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_role_name"), ["name"], unique=True)

    # Create role_permission table if it doesn't exist
    if "role_permission" not in existing_tables:
        op.create_table(
            "role_permission",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("role_id", sa.Uuid(), nullable=False),
            sa.Column("permission_id", sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(["permission_id"], ["permission.id"]),
            sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("role_id", "permission_id", name="unique_role_permission"),
        )

    # Create indexes if they don't exist
    if "role_permission" in inspector.get_table_names():
        existing_indexes = [idx["name"] for idx in inspector.get_indexes("role_permission")]
        with op.batch_alter_table("role_permission", schema=None) as batch_op:
            if "ix_role_permission_permission_id" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_role_permission_permission_id"), ["permission_id"], unique=False)
            if "ix_role_permission_role_id" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_role_permission_role_id"), ["role_id"], unique=False)

    # Create user_role_assignment table if it doesn't exist
    if "user_role_assignment" not in existing_tables:
        op.create_table(
            "user_role_assignment",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("user_id", sa.Uuid(), nullable=False),
            sa.Column("role_id", sa.Uuid(), nullable=False),
            sa.Column("scope_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("scope_id", sa.Uuid(), nullable=True),
            sa.Column("is_immutable", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("created_by", sa.Uuid(), nullable=True),
            sa.ForeignKeyConstraint(["created_by"], ["user.id"]),
            sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("user_id", "role_id", "scope_type", "scope_id", name="unique_user_role_scope"),
        )

    # Create indexes if they don't exist
    if "user_role_assignment" in inspector.get_table_names():
        existing_indexes = [idx["name"] for idx in inspector.get_indexes("user_role_assignment")]
        with op.batch_alter_table("user_role_assignment", schema=None) as batch_op:
            if "idx_scope_lookup" not in existing_indexes:
                batch_op.create_index("idx_scope_lookup", ["user_id", "scope_type", "scope_id"], unique=False)
            if "ix_user_role_assignment_role_id" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_user_role_assignment_role_id"), ["role_id"], unique=False)
            if "ix_user_role_assignment_scope_id" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_user_role_assignment_scope_id"), ["scope_id"], unique=False)
            if "ix_user_role_assignment_scope_type" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_user_role_assignment_scope_type"), ["scope_type"], unique=False)
            if "ix_user_role_assignment_user_id" not in existing_indexes:
                batch_op.create_index(batch_op.f("ix_user_role_assignment_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback RBAC tables.

    WARNING: This will delete all RBAC data including role assignments.
    Use with caution in production environments.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    # Drop user_role_assignment table and indexes
    if "user_role_assignment" in existing_tables:
        with op.batch_alter_table("user_role_assignment", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_user_role_assignment_user_id"))
            batch_op.drop_index(batch_op.f("ix_user_role_assignment_scope_type"))
            batch_op.drop_index(batch_op.f("ix_user_role_assignment_scope_id"))
            batch_op.drop_index(batch_op.f("ix_user_role_assignment_role_id"))
            batch_op.drop_index("idx_scope_lookup")
        op.drop_table("user_role_assignment")

    # Drop role_permission table and indexes
    if "role_permission" in existing_tables:
        with op.batch_alter_table("role_permission", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_role_permission_role_id"))
            batch_op.drop_index(batch_op.f("ix_role_permission_permission_id"))
        op.drop_table("role_permission")

    # Drop role table and indexes
    if "role" in existing_tables:
        with op.batch_alter_table("role", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_role_name"))
        op.drop_table("role")

    # Drop permission table and indexes (updated for final schema)
    if "permission" in existing_tables:
        with op.batch_alter_table("permission", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_permission_scope"))
            batch_op.drop_index(batch_op.f("ix_permission_action"))
        op.drop_table("permission")
    # ### end Alembic commands ###
