"""Add RBAC tables (Role, Permission, RolePermission, UserRoleAssignment)

Revision ID: d645246fd66c
Revises: 3162e83e485f
Create Date: 2025-11-08 13:32:07.162440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langbuilder.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'd645246fd66c'
down_revision: Union[str, None] = '3162e83e485f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolepermission',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='unique_role_permission')
    )
    with op.batch_alter_table('rolepermission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rolepermission_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rolepermission_role_id'), ['role_id'], unique=False)

    op.create_table('userroleassignment',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='unique_user_role_scope')
    )
    with op.batch_alter_table('userroleassignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userroleassignment_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_userroleassignment_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_userroleassignment_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_userroleassignment_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_role_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_scope_lookup'))
        batch_op.drop_index(batch_op.f('ix_user_role_assignment_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_role_assignment_scope_id'))
        batch_op.drop_index(batch_op.f('ix_user_role_assignment_scope_type'))
        batch_op.drop_index(batch_op.f('ix_user_role_assignment_user_id'))

    op.drop_table('user_role_assignment')
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permission_permission_id'))
        batch_op.drop_index(batch_op.f('ix_role_permission_role_id'))

    op.drop_table('role_permission')
    # Update permission table: rename 'action' to 'name', add 'created_at'
    # We need to handle this carefully because of existing data
    with op.batch_alter_table('permission', schema=None) as batch_op:
        # First add new columns as nullable
        batch_op.add_column(sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # Copy data from action to name
    conn.execute(sa.text("UPDATE permission SET name = action"))
    conn.execute(sa.text("UPDATE permission SET created_at = datetime('now')"))

    # Now alter columns to be NOT NULL and drop old column
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_action'))
        batch_op.drop_constraint(batch_op.f('unique_action_scope'), type_='unique')
        batch_op.create_index(batch_op.f('ix_permission_name'), ['name'], unique=False)
        batch_op.create_unique_constraint('unique_permission_scope', ['name', 'scope'])
        batch_op.drop_column('action')

    # Update role table: rename 'is_system' to 'is_system_role', drop 'is_global', add 'created_at'
    with op.batch_alter_table('role', schema=None) as batch_op:
        # First add new columns as nullable
        batch_op.add_column(sa.Column('is_system_role', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # Copy data from is_system to is_system_role
    conn.execute(sa.text("UPDATE role SET is_system_role = is_system"))
    conn.execute(sa.text("UPDATE role SET created_at = datetime('now')"))

    # Now drop old columns
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('is_global')
        batch_op.drop_column('is_system')

    # Performance indexes for UserRoleAssignment lookups (as specified in implementation plan v1.1)
    # These must be created after tables are modified
    op.create_index(
        'idx_user_role_assignment_lookup',
        'userroleassignment',
        ['user_id', 'scope_type', 'scope_id'],
        unique=False
    )

    op.create_index(
        'idx_user_role_assignment_user',
        'userroleassignment',
        ['user_id'],
        unique=False
    )

    op.create_index(
        'idx_user_role_assignment_scope',
        'userroleassignment',
        ['scope_type', 'scope_id'],
        unique=False
    )

    # Performance index for RolePermission joins
    op.create_index(
        'idx_role_permission_lookup',
        'rolepermission',
        ['role_id', 'permission_id'],
        unique=False
    )

    # Performance index for Permission lookups by scope
    op.create_index(
        'idx_permission_name_scope',
        'permission',
        ['name', 'scope'],
        unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop performance indexes before dropping tables
    op.drop_index('idx_permission_name_scope', table_name='permission')
    op.drop_index('idx_role_permission_lookup', table_name='rolepermission')
    op.drop_index('idx_user_role_assignment_scope', table_name='userroleassignment')
    op.drop_index('idx_user_role_assignment_user', table_name='userroleassignment')
    op.drop_index('idx_user_role_assignment_lookup', table_name='userroleassignment')

    # Restore role table columns: add back 'is_system' and 'is_global', remove 'is_system_role' and 'created_at'
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_global', sa.BOOLEAN(), nullable=True))

    # Copy data back
    conn.execute(sa.text("UPDATE role SET is_system = is_system_role"))
    conn.execute(sa.text("UPDATE role SET is_global = 0"))

    # Drop new columns
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_system_role')

    # Restore permission table: add back 'action', remove 'name' and 'created_at'
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=6), nullable=True))

    # Copy data back from name to action
    conn.execute(sa.text("UPDATE permission SET action = name"))

    # Now modify constraints and drop new columns
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint('unique_permission_scope', type_='unique')
        batch_op.drop_index(batch_op.f('ix_permission_name'))
        batch_op.create_unique_constraint(batch_op.f('unique_action_scope'), ['action', 'scope'])
        batch_op.create_index(batch_op.f('ix_permission_action'), ['action'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('name')

    op.create_table('role_permission',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
    sa.Column('permission_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('unique_role_permission'))
    )
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permission_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permission_permission_id'), ['permission_id'], unique=False)

    op.create_table('user_role_assignment',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
    sa.Column('scope_type', sa.VARCHAR(), nullable=False),
    sa.Column('scope_id', sa.CHAR(length=32), nullable=True),
    sa.Column('is_immutable', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name=op.f('unique_user_role_scope'))
    )
    with op.batch_alter_table('user_role_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_assignment_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_assignment_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_assignment_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_assignment_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_scope_lookup'), ['user_id', 'scope_type', 'scope_id'], unique=False)

    with op.batch_alter_table('userroleassignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userroleassignment_user_id'))
        batch_op.drop_index(batch_op.f('ix_userroleassignment_scope_type'))
        batch_op.drop_index(batch_op.f('ix_userroleassignment_scope_id'))
        batch_op.drop_index(batch_op.f('ix_userroleassignment_role_id'))

    op.drop_table('userroleassignment')
    with op.batch_alter_table('rolepermission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rolepermission_role_id'))
        batch_op.drop_index(batch_op.f('ix_rolepermission_permission_id'))

    op.drop_table('rolepermission')
    # ### end Alembic commands ###
