"""Add is_starter_project to Folder for RBAC

Revision ID: e562793da031
Revises: d645246fd66c
Create Date: 2025-11-08 18:02:55.811820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langbuilder.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'e562793da031'
down_revision: Union[str, None] = 'd645246fd66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_starter_project', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_column('is_starter_project')

    # ### end Alembic commands ###
